# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  issues:
    types: [opened]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy 
          pip install scipy
          pip install joblib
          pip install scikit-learn 
          pip install tabulate   
          pip install pandas
          pip install pytest
          pip install tqdm

      # Runs a single command using the runners shell
      - name: execute
        run: python main.py ${{github.event.issue.title}}

      - name: Close Issue
        continue-on-error: true
        uses: peter-evans/close-issue@v1
        with:
          comment: |
            The issue you have reported seems to be resolved now.
            The extracted data can be found at releases.
